# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mande', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='opportunity_email',
            new_name='email',
        ),
    ]
