# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande', '0002_auto_20160419_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, upload_to='/static/mande/uploads/'),
        ),
    ]
