# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mande', '0002_auto_20160405_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_req',
        ),
    ]
