# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-10 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande', '0004_auto_20160510_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_title',
            field=models.CharField(max_length=20),
        ),
    ]
