# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-10 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande', '0005_auto_20160510_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.IntegerField(choices=[(1, 'Babysitting'), (2, 'IT'), (3, 'Ushering')], default=1, max_length=1, verbose_name='Opportunity Type'),
        ),
    ]
